name: deploy to test instance
on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH Setup
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.CICD_SECRET }}
          port: ${{ secrets.PORT }}
          script: |
            cd /apps/github-workflows/mhealth-apps/
            sudo rm -rf ushauri_api
            sudo mkdir ushauri_api
            sudo chown -R cicd2:cicd2 ushauri_api

      - name: Clone Repository
        run: |
          cd /apps/github-workflows/mhealth-apps/ushauri_api
          git clone -b main https://github.com/palladiumkenya/ushauri_api.git .

      - name: Copy Environment File
        run: cp /apps/configs/ushauri_api/.env /apps/github-workflows/mhealth-apps/ushauri_api/

      - name: Build and Deploy Docker Image
        run: |
          cd /apps/github-workflows/mhealth-apps/ushauri_api
          docker stop ushauri_api || true
          docker rm ushauri_api || true
          docker build -t ushauri_api:latest .
          docker run -p 7002:5000 --name ushauri_api -d --restart always ushauri_api:latest
