name: deploy to test instance
on:
  push:
    branches: [ main ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          cd /apps/github-workflows/mhealth-apps/
          sudo rm -rf ushauri_api
          sudo mkdir ushauri_api
          sudo chown -R cicd2:cicd2 ushauri_api
          git config --global --add safe.directory /apps/github-workflows/mhealth-apps/ushauri_api
          cd ushauri_api
          git clone -b main https://github.com/palladiumkenya/ushauri_api.git .
          # cp  /apps/configs/ushauri_api/node.dockerfile /apps/github-workflows/mhealth-apps/ushauri_api/
          cp  /apps/configs/ushauri_api/.env /apps/github-workflows/mhealth-apps/ushauri_api/
          # cp  /apps/configs/ushauri_api/nginx.dockerfile /apps/github-workflows/mhealth-apps/ushauri_api/
          # cp -r /apps/configs/ushauri_api/nginx/ /apps/github-workflows/mhealth-apps/ushauri_api/
          # cp  /apps/configs/ushauri_api/docker-compose.yml /apps/github-workflows/mhealth-apps/ushauri_api/
          docker build -t ushauri_api:latest .
          docker stop ushauri_api 
          docker rm ushauri_api 
          docker run -p 7002:5000 --name ushauri_api -d --restart always ushauri_api:latest         
